### ISSUE TITLE
Plot_network function fails

### ISSUE THREAD

**Issue by noahrhodes** [lanl-ansi/PowerModelsAnalytics.jl#5]
Plot network gives an error when attempting to plot.  Can you replicate the issue?

It was working fine for me over the weekend, and I haven't been able to track the issue.

```
julia> plot_network(_PMs.parse_file("../cases/case24.m"))
ERROR: Cannot convert Float64 to series data for plotting
```

_Project.toml contents_
[deps]
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
PowerModelsAnalytics = "7425d11c-6b70-11e9-2bc6-9bcd3191d4b9"

**Comment by pseudocubic** [comment]
I'm wasn't able to reproduce this error on the latest version (master / v0.1.0). 

You might want to try both `free PowerModelsAnalytics` and `]rm PowerModelsAnalytics` from your environment, then use `]gc` to garbage collect old versions and then `]add PowerModelsAnalytics` again. If you want to use the version compatible with `PowerModels#v13-rc`, you can use `PowerModelsAnalytics#pms-v0.13`

**Comment by noahrhodes** [comment]
Is the branch `PowerModelsAnalytics#pms-v0.13` public?

**Comment by pseudocubic** [comment]
Apologies, I didn't push it to remote, its there now

**Comment by pseudocubic** [comment]
@noahrhodes was your issue resolved?

**Comment by noahrhodes** [comment]
I believe so. 

I was able to make plot_network work in a new environment with the power models 0.13 branches, but I'm waiting for my pull request in PowerModelsResoration to be merged and rebased before closing this.

I want to be sure that it wasn't caused by a solution reporting issue.

**Comment by noahrhodes** [comment]
working on pms13 branch.  Likely resolved by running garbage collect on old packages.
